
services:
  # IRIS for Health服务
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
            IRIS_USERNAME: superuser
            IRIS_PASSWORD: SYS
    hostname: mcpdemo
    container_name: IRIS_For_Health
    ports: 
      - 1980:1972
      - 52880:52773
      - 53773
      - 50080:80

  # Chainlit应用服务
  chainlit-app:
    build:
      context: ./chainlit-app
      dockerfile: Dockerfile
    container_name: chainlit-app
    ports:
      - "8000:8000"  # Chainlit默认端口
    environment:
      - CHAINLIT_HOST=0.0.0.0
      - CHAINLIT_PORT=8000
    restart: always